#============================================================================
# euler029
# 6/22/12
#
# How many distinct terms are in the sequence
# generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
#============================================================================

def soln
  list = []
  (2..100).each do |a|
    (2..100).each { |b| list.push(a ** b) }
  end
  list.uniq!.count
end

#=====================================
# Run
#=====================================

es = EulerSolution.new({:soln => soln})
es.run
